### ISSUE TITLE
프로젝트 home 화면

### ISSUE THREAD

**Issue by limJaemin99** [limJaemin99/TeamPlus#19]

**Comment by limJaemin99** [comment]
#18 프로젝트 home 화면 생성 - 초기 화면 및 메뉴바 설정

**Comment by limJaemin99** [comment]
#20 프로젝트 home 화면 - 프로젝트 참가
프로젝트 home 화면 중 프로젝트 참가 및 사이드바 수정

**Comment by limJaemin99** [comment]
#21 프로젝트 home 화면 - 프로젝트 리스트 , 생성

**Comment by HongSeungHee25** [comment]
test

**Comment by limJaemin99** [comment]
**[예시]**
#21 해당 커밋에서 작업한 내용 설명 1~2줄
- testController.java
- test.html
- 위와 같이 사용한 파일명 작성
